### ISSUE TITLE
Fatal Crash: Concurrent Map Writes (v1.0.0)

### ISSUE THREAD

**Issue by AdamCoulterOz** [arkiaconsulting/terraform-provider-akc#23]
This line is causing a fatal crash:

https://github.com/arkiaconsulting/terraform-provider-akc/blob/389597220ff8dd1aa5d585f73bf9c977904d43ef/akc/helpers.go#L22

@arkiaconsulting, can we please revert to letting terraform handle the lifetime of the client objects?

```
Stack trace from the terraform-provider-akc_1.0.0 plugin:

fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 72 [running]:
runtime.throw(0x18b5f6a, 0x15)
        runtime/panic.go:1117 +0x72 fp=0xc0006f9608 sp=0xc0006f95d8 pc=0x1035d52
runtime.mapassign_faststr(0x17c6c00, 0xc00019b9b0, 0xc0006ca860, 0x1b, 0x0)
        runtime/map_faststr.go:291 +0x3d8 fp=0xc0006f9670 sp=0xc0006f9608 pc=0x10142d8
github.com/arkiaconsulting/terraform-provider-akc/akc.getOrReuseClient(0xc0006ca860, 0x1b, 0xc0006b2900, 0x1794b00, 0xc0006e48e0, 0x1)
        github.com/arkiaconsulting/terraform-provider-akc/akc/helpers.go:22 +0xd2 fp=0xc0006f96b0 sp=0xc0006f9670 pc=0x151bef2
github.com/arkiaconsulting/terraform-provider-akc/akc.dataSourceKeyValueRead(0xc000199500, 0x17b29e0, 0xc0006b2900, 0x1e16ac0, 0xc00007c480)
        github.com/arkiaconsulting/terraform-provider-akc/akc/data_source_key_value.go:44 +0x245 fp=0xc0006f98e8 sp=0xc0006f96b0 pc=0x151b565
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0001a2700, 0x19a3218, 0xc0006b2d80, 0xc000199500, 0x17b29e0, 0xc0006b2900, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:335 +0x1ee fp=0xc0006f9958 sp=0xc0006f98e8 pc=0x14f754e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc0001a2700, 0x19a3218, 0xc0006b2d80, 0xc0004bcc40, 0x17b29e0, 0xc0006b2900, 0xc0006b2900, 0xc0004bcc40, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/resource.go:558 +0xfd fp=0xc0006f99e0 sp=0xc0006f9958 pc=0x14f919d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00000d560, 0x19a3218, 0xc0006b2d80, 0xc0004bcb60, 0xc0006b2d80, 0x100b665, 0x1844d60)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/schema/grpc_provider.go:1105 +0x4d6 fp=0xc0006f9ae0 sp=0xc0006f99e0 pc=0x14f0d76
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadDataSource(0xc00061fd00, 0x19a32c0, 0xc0006b2d80, 0xc0006b58b0, 0xc00061fd00, 0xc0006dcb40, 0xc00065bba0)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:247 +0xe5 fp=0xc0006f9b40 sp=0xc0006f9ae0 pc=0x17143c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0x18739e0, 0xc00061fd00, 0x19a32c0, 0xc0006dcb40, 0xc000055800, 0x0, 0x19a32c0, 0xc0006dcb40, 0xc0001f60e0, 0x61)
        github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214 fp=0xc0006f9bb0 sp=0xc0006f9b40 pc=0x170c4d4
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002356c0, 0x19aa978, 0xc000316f00, 0xc0006bc300, 0xc0003026c0, 0x1dd9e30, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b fp=0xc0006f9e50 sp=0xc0006f9bb0 pc=0x16b6dcb
google.golang.org/grpc.(*Server).handleStream(0xc0002356c0, 0x19aa978, 0xc000316f00, 0xc0006bc300, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c fp=0xc0006f9f68 sp=0xc0006f9e50 pc=0x16baf8c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000114170, 0xc0002356c0, 0x19aa978, 0xc000316f00, 0xc0006bc300)
        google.golang.org/grpc@v1.32.0/server.go:859 +0xab fp=0xc0006f9fb8 sp=0xc0006f9f68 pc=0x16c8f4b
runtime.goexit()
        runtime/asm_amd64.s:1371 +0x1 fp=0xc0006f9fc0 sp=0xc0006f9fb8 pc=0x106c001
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0xc00033be90)
        github.com/hashicorp/go-plugin@v1.4.1/server.go:469 +0x954
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0xc0001dab40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/plugin/serve.go:122 +0xf4
main.main()
        github.com/arkiaconsulting/terraform-provider-akc/main.go:10 +0x45

goroutine 12 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0xc000302450, 0x0, 0x0, 0x0)
        github.com/hashicorp/go-plugin@v1.4.1/grpc_broker.go:121 +0x86
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0xc0000980a0)
        github.com/hashicorp/go-plugin@v1.4.1/grpc_broker.go:411 +0x7a
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
        github.com/hashicorp/go-plugin@v1.4.1/grpc_server.go:85 +0x39c

goroutine 13 [IO wait]:
internal/poll.runtime_pollWait(0x6f53a58, 0x72, 0xffffffffffffffff)
        runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00010c138, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
        internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00010c120, 0xc0002fb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        internal/poll/fd_unix.go:166 +0x1d5
os.(*File).read(...)
        os/file_posix.go:31
os.(*File).Read(0xc000306020, 0xc0002fb000, 0x1000, 0x1000, 0x400, 0x1796e60, 0x1)
        os/file.go:117 +0x77
bufio.(*Reader).Read(0xc000126f50, 0xc0000d6400, 0x400, 0x400, 0x0, 0x0, 0x0)
        bufio/bufio.go:227 +0x222
github.com/hashicorp/go-plugin.copyChan(0x19ae988, 0xc000212230, 0xc000050a20, 0x1994d20, 0xc000306020)
        github.com/hashicorp/go-plugin@v1.4.1/grpc_stdio.go:181 +0xc5
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
        github.com/hashicorp/go-plugin@v1.4.1/grpc_stdio.go:37 +0xb1

goroutine 14 [IO wait]:
internal/poll.runtime_pollWait(0x6f53888, 0x72, 0xffffffffffffffff)
        runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc00010c1f8, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
        internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00010c1e0, 0xc00058c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        internal/poll/fd_unix.go:166 +0x1d5
os.(*File).read(...)
        os/file_posix.go:31
os.(*File).Read(0xc000306040, 0xc00058c000, 0x1000, 0x1000, 0x400, 0x1796e60, 0x1)
        os/file.go:117 +0x77
bufio.(*Reader).Read(0xc000127750, 0xc0000d6800, 0x400, 0x400, 0x0, 0x0, 0x0)
        bufio/bufio.go:227 +0x222
github.com/hashicorp/go-plugin.copyChan(0x19ae988, 0xc000212230, 0xc000050a80, 0x1994d20, 0xc000306040)
        github.com/hashicorp/go-plugin@v1.4.1/grpc_stdio.go:181 +0xc5
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
        github.com/hashicorp/go-plugin@v1.4.1/grpc_stdio.go:38 +0xfe

goroutine 21 [syscall]:
os/signal.signal_recv(0x0)
        runtime/sigqueue.go:165 +0x9d
os/signal.loop()
        os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        os/signal/signal.go:151 +0x45

goroutine 22 [chan receive]:
github.com/hashicorp/go-plugin.Serve.func3(0xc00010c300, 0x19ae988, 0xc000212230)
        github.com/hashicorp/go-plugin@v1.4.1/server.go:434 +0x89

Error: The terraform-provider-akc_1.0.0 plugin crashed!

```

**Comment by arkiaman** [comment]
Fixed in [1.0.2](https://github.com/arkiaconsulting/terraform-provider-akc/releases/tag/v1.0.2)
