### ISSUE TITLE
Getting provider plugin crash

### ISSUE THREAD

**Issue by AdamCoulterOz** [arkiaconsulting/terraform-provider-akc#31]
```
Stack trace from the terraform-provider-akc_1.1.1.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x10720b7]

goroutine 44 [running]:
github.com/Azure/go-autorest/autorest/adal.(*ServicePrincipalToken).refreshInternal(0xc000393500, 0x1a890a0, 0xc00004e098, 0xc0004a5480, 0x1b, 0x0, 0x0)
        github.com/Azure/go-autorest/autorest/adal@v0.8.2/token.go:913 +0x717
github.com/Azure/go-autorest/autorest/adal.(*ServicePrincipalToken).EnsureFreshWithContext(0xc000393500, 0x1a890a0, 0xc00004e098, 0x0, 0x0)
        github.com/Azure/go-autorest/autorest/adal@v0.8.2/token.go:779 +0x1b4
github.com/Azure/go-autorest/autorest.(*BearerAuthorizer).WithAuthorization.func1.1(0xc0000f1600, 0xc000178480, 0x1c44371aec8, 0xf8)
        github.com/Azure/go-autorest/autorest@v0.10.0/authorization.go:122 +0x112
github.com/Azure/go-autorest/autorest.PreparerFunc.Prepare(0xc000480e20, 0xc0000f1600, 0x0, 0xc00048a000, 0x0)
        github.com/Azure/go-autorest/autorest@v0.10.0/preparer.go:76 +0x37
github.com/Azure/go-autorest/autorest.WithMethod.func1.1(0xc0000f1600, 0x18b8f40, 0x1, 0xc0000f1600)
        github.com/Azure/go-autorest/autorest@v0.10.0/preparer.go:203 +0x58
github.com/Azure/go-autorest/autorest.PreparerFunc.Prepare(0xc00017c3c0, 0xc0000f1600, 0x3, 0xc0004a5540, 0x1a)
        github.com/Azure/go-autorest/autorest@v0.10.0/preparer.go:76 +0x37
github.com/arkiaconsulting/terraform-provider-akc/client.(*Client).send(0xc0004b0d68, 0x18ccd65, 0x3, 0xc0004a5540, 0x1a, 0xc000157b38, 0x1, 0x1, 0xb9dbadfc36ff669d, 0x8, ...)
        github.com/arkiaconsulting/terraform-provider-akc/client/client.go:241 +0xf1
github.com/arkiaconsulting/terraform-provider-akc/client.(*Client).GetKeyValue(0xc0004b0d68, 0x18ccd65, 0x3, 0xc00049b3c8, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/arkiaconsulting/terraform-provider-akc/client/client.go:96 +0x153
github.com/arkiaconsulting/terraform-provider-akc/akc.dataSourceKeyValueRead.func1(0x2)
        github.com/arkiaconsulting/terraform-provider-akc/akc/data_source_key_value.go:55 +0xd8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.RetryContext.func1(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/resource/wait.go:27 +0x62
github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext.func1(0xc000136600, 0xc00014a3f0, 0xc0000153e0, 0xc000176380, 0xc000493870, 0xc000493868)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/resource/state.go:110 +0x309
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/resource.(*StateChangeConf).WaitForStateContext
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.7.0/helper/resource/state.go:83 +0x1d9

Error: The terraform-provider-akc_1.1.1.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by AdamCoulterOz** [comment]
It could be a bug with the `Azure/go-autorest` libraries. Can we try upgrading them to the latest?

	github.com/Azure/go-autorest/autorest v0.10.0 -> v0.11.19
	github.com/Azure/go-autorest/autorest/azure/auth v0.4.2 -> v0.5.8

**Comment by AdamCoulterOz** [comment]
I have found the differential. This occurs when running on Azure compute which has system assigned identity enabled. I did have the service principal authentication enabled though through `ARM_CLIENT_ID`, `ARM_CLIENT_SECRET`, `ARM_TENANT_ID`

**Comment by arkiaman** [comment]
@AdamCoulterOz Sorry for the late reply, I was in holidays. Still an issue ?

**Comment by AdamCoulterOz** [comment]
to fix it I disabled managed identity ... so i've worked around it, but cant get it work with MSI still

**Comment by arkiaman** [comment]
@AdamCoulterOz May be fixed with #34. Waiting for your feedback

**Comment by AdamCoulterOz** [comment]
I'll take a look, thanks mate

**Comment by AdamCoulterOz** [comment]
looks great.
